## Target Guided Ordinal encoding

It is a technique used to encode categorical variables based on thier relationship with the 
target variable. This encoding technique is useful when we have a categorical variable with 
a large number of unique categiries and we want to use this variable as a feature in our machine
learning model.

In target Guided Ordinal Encoding , we replace each category in the categorical variable with a numerical value based on the median or meann of the target 
variable for that category. This creates a monotonic relationship between the categorical variable and the targert variable which can improve the predictive power of the model.

In [11]:
import pandas as pd
df=pd.DataFrame({"cities":["New York","London","Paris","Tokyo","London","Paris"],
                 "price":[100,200,300,400,500,600],
                 })

In [12]:
df

     cities  price
0  New York    100
1    London    200
2     Paris    300
3     Tokyo    400
4    London    500
5     Paris    600

In [14]:
mean_price=df.groupby("cities")["price"].mean().to_dict()
mean_price

{'London': 350.0, 'New York': 100.0, 'Paris': 450.0, 'Tokyo': 400.0}

In [15]:
df["city_encoded"]=df["cities"].map(mean_price)
df

     cities  price  city_encoded
0  New York    100         100.0
1    London    200         350.0
2     Paris    300         450.0
3     Tokyo    400         400.0
4    London    500         350.0
5     Paris    600         450.0

In [1]:
import seaborn as sns

In [3]:
tips_df=sns.load_dataset('tips')

In [4]:
tips_df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [9]:
import pandas as pd
tips_df=pd.DataFrame(tips_df.to_dict())
tips_df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
tips_mean=tips_df.groupby('time')['tip'].mean().to_dict()
tips_mean

{'Dinner': 3.102670454545455, 'Lunch': 2.7280882352941176}

In [13]:
tips_df["mean_tip"]=tips_df.map(tips_mean)
tips_df

TypeError: the first argument must be callable

In [16]:
tips_df["mean_tip"]=tips_df["time"].map(tips_mean)
tips_df.tail()

     total_bill   tip     sex smoker   day    time  size  mean_tip
239       29.03  5.92    Male     No   Sat  Dinner     3   3.10267
240       27.18  2.00  Female    Yes   Sat  Dinner     2   3.10267
241       22.67  2.00    Male    Yes   Sat  Dinner     2   3.10267
242       17.82  1.75    Male     No   Sat  Dinner     2   3.10267
243       18.78  3.00  Female     No  Thur  Dinner     2   3.10267